### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by Thoughtscript** [kleros/kleros-the-schelling-game-api#1]
@n1c01a5 - Thanks for the great chat earlier about this. We sketched out a few ideas briefly and I wanted to think about this a bit more.

Do you think something like:

1.  A _WS / WebSocket_ server that _propogates_ a _question_
2. Then tabulates all connected users's _responses_ calculating the median answer and then the Schelling Point from that first data point.
3. Then Level's up any connected players who answered with the Shelling Point.
4. And (optionally) punishes players who didn't answer in line with the Shelling Point by reducing their level.

Cheers from the Bay!

**Comment by n1c01a5** [comment]
Yeah it could be interesting to make a Shelling Point with the almost instantaneous especially maybe to do short prediction (ex: sports betting with the current match). Of course more we have participants more the prediction means correct. In the first version I don't expect to have enough participants (>100 ?) to make this kind of game (maybe I'm wrong :p) but it could be a nice evolution.
